### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SamCreamer** [djangodeployment/django-deployment-book#12]
"If you want don't know what to do"

First section of the web server chapter

**Comment by SamCreamer** [comment]
(believe it's supposed to be "If you don't know what to do" or "If you don't know what you want to do")

**Comment by aptiko** [comment]
Hi. This is a duplicate of #5, which I just fixed. Thanks anyway for reporting.

BTW, the book is now also available online at https://djangodeployment.readthedocs.io/

**Comment by SamCreamer** [comment]
Thanks, love the book
